config/routes.rb
Rails.application.routes.draw do
  resources :empresas

  resources :municipios

  resources :clientes

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
		# Validar que los atributos sean obligatorios
		validates :cedula, :presence => true
		validates :nombre, :presence => true
		validates :fch_ncto, :presence => true
		validates :mail, :presence => true
		# validar un atributo booleano
		# validar que un atributos unicos
		validates :cedula, uniqueness: { message: "No se puede Repetir" }
		validates :mail,
		uniqueness: { message: "No se puede Repetir" }
		validates :genero, inclusion: [true, false]
		# validar formato de un email
		validates :mail, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
		message: 'Formato no valido' }
		# valida la longitud de un campo, tanto la longitud minima como la maxima
		validates :cedula, length: { minimum: 5, maximum: 10 }
		validates :nombre, length: { minimum: 5, maximum: 50 }
		# Valida si un atributo es numerico
        validates :cedula, numericality: true
		def self.search(search, page)
			where(['upper(nombre) like ?',
			"%#{search}%".upcase]).paginate(page: page, per_page: 5).order("nombre")
		end
   

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	
	belongs_to :municipio
    def self.search(search, page)
     where(['upper(razon_social) like ?', "%#{search}%".upcase]).paginate(page: page, per_page: 1).order("razon_social")
  end
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
	has_many :empresas
      def self.search(search, page)
     where(['upper(nombre) like ?', "%#{search}%".upcase]).paginate(page: page, per_page: 1).order("nombre")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.search(params[:search], params[:page])
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:cedula, :nombre, :mail, :genero, :fch_ncto, :celular)
    end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas =Empresa.search(params[:search], params[:page])
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nit, :razon_social, :gerente, :direccion, :email, :telefono, :fch_creacion, :nro_trabajadores, :municipio_id)
    end
end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  before_action :set_municipio, only: [:show, :edit, :update, :destroy]

  # GET /municipios
  # GET /municipios.json
  def index
    @municipios = Municipio.search(params[:search], params[:page])
  end

  # GET /municipios/1
  # GET /municipios/1.json
  def show
  end

  # GET /municipios/new
  def new
    @municipio = Municipio.new
  end

  # GET /municipios/1/edit
  def edit
  end

  # POST /municipios
  # POST /municipios.json
  def create
    @municipio = Municipio.new(municipio_params)

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to @municipio, notice: 'Municipio was successfully created.' }
        format.json { render :show, status: :created, location: @municipio }
      else
        format.html { render :new }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipios/1
  # PATCH/PUT /municipios/1.json
  def update
    respond_to do |format|
      if @municipio.update(municipio_params)
        format.html { redirect_to @municipio, notice: 'Municipio was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipio }
      else
        format.html { render :edit }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipios/1
  # DELETE /municipios/1.json
  def destroy
    @municipio.destroy
    respond_to do |format|
      format.html { redirect_to municipios_url, notice: 'Municipio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipio
      @municipio = Municipio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipio_params
      params.require(:municipio).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper

   def mostrar_genero(genero)
       if genero
          "Masculino"
       else
          "Femenino"
       end
   end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
	def tamano_empresa(n)
   	   if n <= 10
   	   	  "Micro"
   	   elsif n > 10 and n <= 50
   	   	  "Mediana"
   	   elsif n > 50
   	   	  "Grande"
       else
       	  "No tiene valor"
   	   end
   end
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    Masculino: <%= f.radio_button(:genero, true) %>
    Femenino: <%= f.radio_button(:genero, false) %>
  </div>
  <div class="field">
    <%= f.label :fch_ncto %><br>
    <%= f.date_select :fch_ncto %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar cliente</h1>

<%= render 'form' %>

<%= link_to 'Ver', @cliente %> |
<%= link_to 'Atras', clientes_path %>

app/views/clientes/index.html.erb
<h1>Lista de clientes</h1>
<%= form_tag clientes_path, :method => 'get' do %>
 <% content_tag :label do %>
  Buscar termino:
   <%= text_field_tag :search, params[:search] %>
   <%= submit_tag "Buscar", :name => nil %>
 <% end %>
<% end %>
<br>
<table>
  <thead>
    <tr>
      <th>Cedula</th>
      <th>Nombre</th>
      <th>Mail</th>
      <th>Genero</th>
      <th>Fch nacimiento</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.cedula %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.mail %></td>
        <td><%= mostrar_genero(cliente.genero) %></td>
        <td><%= cliente.fch_ncto %></td>
        <td><%= cliente.celular %></td>
        <td><%= link_to 'Ver', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Seguro quieres eliminar el archivo?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo cliente', new_cliente_path %>
<%= will_paginate @clientes, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>
Clientes: <%= @clientes.count %>

app/views/clientes/new.html.erb
<h1>Nuevo cliente</h1>

<%= render 'Formulario' %>

<%= link_to 'Atras', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula:</strong>
  <%= @cliente.cedula %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @cliente.mail %>
</p>

<p>
<strong>Genero:</strong>
<%= mostrar_genero(@cliente.genero) %>
</p>

<p>
  <strong>Fch nacimiento:</strong>
  <%= @cliente.fch_ncto %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @cliente.celular %>
</p>



<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Anterior', clientes_path %>

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nit %><br>
    <%= f.text_field :nit %>
  </div>
  <div class="field">
    <%= f.label :razon_social %><br>
    <%= f.text_field :razon_social %>
  </div>
  <div class="field">
    <%= f.label :gerente %><br>
    <%= f.text_field :gerente %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :fch_creacion %><br>
    <%= f.date_select :fch_creacion %>
  </div>
  <div class="field">
    <%= f.label :nro_trabajadores %><br>
    <%= f.number_field :nro_trabajadores %>
  </div>
 <div class="field"> 
     Municipio Ubicación <br>
     <%= f.collection_select :municipio_id, Municipio.all, :id, :nombre, class: "form-control", prompt: 
     "Seleccione Municipio" %> 
 </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editar  empresa</h1>

<%= render 'form' %>

<%= link_to 'Ver', @empresa %> |
<%= link_to 'Atras', empresas_path %>

app/views/empresas/index.html.erb
<h1>Listing empresas</h1>
<%= form_tag empresas_path, :method => 'get' do %>
 <% content_tag :label do %>
   Buscar Nombre
   <%= text_field_tag :search, params[:search] %>
   <%= submit_tag "Buscar", :name => nil %>
 <% end %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Nit</th>
      <th>Razon social</th>
      <th>Gerente</th>
      <th>Direccion</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Fch creacion</th>
      <th>Nro trabajadores</th>
      <th>Tamaño</th>
      <th>Municipio</th>
      <th>Tamaño de empresa<th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nit %></td>
        <td><%= empresa.razon_social %></td>
        <td><%= empresa.gerente %></td>
        <td><%= empresa.direccion %></td>
        <td><%= empresa.email %></td>
        <td><%= empresa.telefono %></td>
        <td><%= empresa.fch_creacion %></td>
        <td><%= empresa.nro_trabajadores %></td>
        <td><%= tamano_empresa(empresa.nro_trabajadores) rescue nil%></td>
        <td><%= empresa.municipio.nombre rescue nil %></td>
        <td><%= link_to 'Ver', empresa %></td>
        <td><%= link_to 'Editar', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Eliminar', empresa, method: :delete, data: { confirm: 'Seguro que que quieres eliminar este archivo?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Empresa', new_empresa_path %>
<%= will_paginate @empresas, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>
Empresas: <%= @empresas.count %>

app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render 'form' %>

<%= link_to 'Atras', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nit:</strong>
  <%= @empresa.nit %>
</p>

<p>
  <strong>Razon social:</strong>
  <%= @empresa.razon_social %>
</p>

<p>
  <strong>Gerente:</strong>
  <%= @empresa.gerente %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @empresa.direccion %>
</p>

<p>
  <strong>Email:</strong>
  <%= @empresa.email %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @empresa.telefono %>
</p>

<p>
  <strong>Fch creacion:</strong>
  <%= @empresa.fch_creacion %>
</p>

<p>
  <strong>Nro trabajadores:</strong>
  <%= @empresa.nro_trabajadores %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @empresa.municipio.nombre rescue nil%>
</p>

<%= link_to 'Editar', edit_empresa_path(@empresa) %> |
<%= link_to 'Atras', empresas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paginacion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/municipios/_form.html.erb
<%= form_for(@municipio) do |f| %>
  <% if @municipio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@municipio.errors.count, "error") %> prohibited this municipio from being saved:</h2>

      <ul>
      <% @municipio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/municipios/edit.html.erb
<h1>Editing municipio</h1>

<%= render 'form' %>

<%= link_to 'ver', @municipio %> |
<%= link_to 'Atras', municipios_path %>

app/views/municipios/index.html.erb
<h1>Lista de municipios</h1>
<%= form_tag municipios_path, :method => 'get' do %>
 <% content_tag :label do %>
   Search term:
   <%= text_field_tag :search, params[:search] %>
   <%= submit_tag "Buscar", :name => nil %>
 <% end %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipios.each do |municipio| %>
      <tr>
        <td><%= municipio.nombre %></td>
        <td><%= link_to 'Show', municipio %></td>
        <td><%= link_to 'Edit', edit_municipio_path(municipio) %></td>
        <td><%= link_to 'Destroy', municipio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Municipio', new_municipio_path %>
<%= will_paginate @municipios, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>
Municipios: <%= @municipios.count %>

app/views/municipios/new.html.erb
<h1>New municipio</h1>

<%= render 'form' %>

<%= link_to 'Back', municipios_path %>

app/views/municipios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @municipio.nombre %>
</p>

<%= link_to 'Edit', edit_municipio_path(@municipio) %> |
<%= link_to 'Back', municipios_path %>